<a href="https://colab.research.google.com/github/anjanasuresh14/INTRODUCTION-TO-PYTHON/blob/main/Python13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files
supermarket=files.upload()

Saving Supermarket_sales.csv to Supermarket_sales.csv


In [47]:
import pandas as pd
dataframe=pd.read_csv('Supermarket_sales.csv')
'''print(dataframe.head(10))
print(dataframe.tail(8))
dataframe[['City','Branch']]
dataframe.drop('Tax',axis=1)
dataframe.drop('gross_margin_percentage',axis=1)
dataframe.drop([2],axis=0)
max_overall=dataframe.Unitprice.idxmax()
print(max_overall)
min_overall=dataframe.Unitprice.mean()
print(min_overall)
print(dataframe.loc[dataframe['Customertype']=='Normal'])'''
print(dataframe.loc[dataframe['Gender']=='Male'])

      No    InvoiceID Branch       City Customertype  Gender  \
1      2  226-31-3081      C  Naypyitaw       Normal  Female   
2      3  631-41-3108      A     Yangon       Normal    Male   
4      5  373-73-7910      A     Yangon       Normal    Male   
5      6  699-14-3026      C  Naypyitaw       Normal    Male   
7      8  315-22-5665      C  Naypyitaw       Normal  Female   
..   ...          ...    ...        ...          ...     ...   
992  993  745-74-0715      A     Yangon       Normal    Male   
993  994  690-01-6631      B   Mandalay       Normal    Male   
995  996  233-67-5758      C  Naypyitaw       Normal    Male   
996  997  303-96-2227      B   Mandalay       Normal  Female   
998  999  347-56-2442      A     Yangon       Normal    Male   

                Productline  Unitprice  Quantity      Tax      Total  \
1    Electronic accessories      15.28         5   3.8200    80.2200   
2        Home and lifestyle      46.33         7  16.2155   340.5255   
4         Sport

In [48]:
import numpy as np
L=[1,2,3,4,5,6,7,8,9,10]
D=np.array(L)
print(D)

[ 1  2  3  4  5  6  7  8  9 10]


In [52]:
import numpy as np
m1=[[12,14,10],[15,19,20],[11,15,19]]
marray=np.array(m1)
print(marray)

[[12 14 10]
 [15 19 20]
 [11 15 19]]


In [51]:
import numpy as np
m=[[12,13],[13,14],[15,16],[17,18]]
m1array=np.array(m)
print(m1array)

[[12 13]
 [13 14]
 [15 16]
 [17 18]]


In [53]:
v1=np.arange(20)
print(v1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [54]:
v2=np.arange(1,11)
print(v2)

[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
v2=np.arange(5,11)
print(v2)

[ 5  6  7  8  9 10]


In [58]:
v3=np.arange(70,100,3)
print(v3)

[70 73 76 79 82 85 88 91 94 97]


In [59]:
z=np.zeros((2,6))
print(z)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [61]:
o=np.ones(6)
print(o)

[1. 1. 1. 1. 1. 1.]


In [63]:
o1=np.ones((8,2))
print(o1)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [66]:
i=np.eye(10)
print(i)
len(i)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


10

In [73]:
f=np.array([[1,2,3],[4,5,6],[7,8,9],[4,0,7]])
print(f.reshape(6,2))

[[1 2]
 [3 4]
 [5 6]
 [7 8]
 [9 4]
 [0 7]]


In [76]:
v=np.random.randint(44,88,6)
print(v)

[68 75 79 83 47 71]


In [77]:
v=np.random.randint(25,50,(4,3))
print(v)

[[46 28 29]
 [33 44 33]
 [44 47 49]
 [34 31 34]]
